name: "Test"
on:
  [push, pull_request]

jobs:
  test:
    name: "Power Test"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    # - name: ZAP Scan
    #   uses: zaproxy/action-baseline@v0.4.0
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     docker_name: 'owasp/zap2docker-stable'
    #     target: 'http://testhtml5.vulnweb.com'

    # Part 1
    - name: Docker run - OWASP ZAP Baseline Scan
        # This ZAP Scan is ran from a Docker Image
        # The command below is basically the exact command that is used to run ZAP Scan
        # from a Docker Image
        # More details here: https://www.zaproxy.org/docs/docker/about/
      run: |
        docker run -v S\:\\K\\Haxx\\codes\\automation-power:/zap/wrk:rw -t owasp/zap2docker-stable zap-baseline.py -t http://testhtml5.vulnweb.com -g alerts.conf -J test2.json
        
    # Part 2
    - name: Python Power
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install Dependencies
      run: |
        pip install jira
        pip install click
    
    - name: Python Test
    - run: |
        python3 power.py
    - run: |
        python3 power.py
    - run: |
        python3 power.py
    - run: |
        python3 power.py
    
      
    

